version: "3.5"

services:
  jekyll:
    container_name: splash
    build:
      context: ./
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -w --force_polling -H 0.0.0.0 -t
